// <auto-generated />
using CodeFirstCRUD.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirstCRUD.Migrations
{
    [DbContext(typeof(KisiDB))]
    partial class KisiDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CodeFirstCRUD.Models.Kisi", b =>
                {
                    b.Property<int>("KisiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KisiID"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("KisiID");

                    b.ToTable("Kisiler");

                    b.HasData(
                        new
                        {
                            KisiID = 1,
                            Ad = "Burak",
                            Soyad = "Kilicaslan",
                            Telefon = "5554443322"
                        },
                        new
                        {
                            KisiID = 2,
                            Ad = "Beyza",
                            Soyad = "Kilicaslan",
                            Telefon = "9990001122"
                        },
                        new
                        {
                            KisiID = 3,
                            Ad = "John",
                            Soyad = "Doe",
                            Telefon = "5555555555"
                        },
                        new
                        {
                            KisiID = 4,
                            Ad = "Nancy",
                            Soyad = "Grancer",
                            Telefon = "7778889900"
                        },
                        new
                        {
                            KisiID = 5,
                            Ad = "David",
                            Soyad = "Concord",
                            Telefon = "3334058725"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
